repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args: ['--branch', 'master']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
