# Test your FastAPI endpoints

GET http://localhost:8080/
Accept: application/json

###

GET http://localhost:8080/health
Accept: application/json

###

GET http://localhost:8080/health/db
Accept: application/json

###

POST http://localhost:8080/health/echo
Content-Type: application/json

{ "key" : "value", "list": [1, 2, 3] }

###

GET http://localhost:8080/v1/analysis?q=ПЦР
Content-Type: application/json

###

GET http://localhost:8080/v1/analysis/d13b509a-9d02-49a3-be71-96fcb80c4c37
Content-Type: application/json

###
