# Test your FastAPI endpoints

GET http://localhost:8080/
Accept: application/json

###

GET http://localhost:8080/health
Accept: application/json

###

GET http://localhost:8080/health/db
Accept: application/json

###

POST http://localhost:8080/health/echo
Content-Type: application/json

{ "key" : "value", "list": [1, 2, 3] }

###

GET http://localhost:8080/v1/analysis?q=ПЦР&city=Москва
Content-Type: application/json

###

GET http://localhost:8080/v1/analysis/d13b509a-9d02-49a3-be71-96fcb80c4c37
Content-Type: application/json

###

GET http://localhost:8080/v1/city
Content-Type: application/json

###

POST http://localhost:8080/v1/user/register
Content-Type: application/json

{
  "email": "king.arthur@camelot.bt",
  "name": "Artur",
  "password": "guinevere"
}

###

POST http://localhost:8080/v1/user/jwt/login
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="username"

king.arthur@camelot.bt

--boundary
Content-Disposition: form-data; name="password"

guinevere
--boundary--

###

GET http://localhost:8080/v1/user/jwt/logout
Content-Type: application/json

###

GET http://localhost:8080/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMyIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0Njc5OTYyfQ.ufqei1C91wTA_-wZdmmrSyiUF0R_czIPLhkK9JKhEq0
Content-Type: application/json

###

