# Test your FastAPI endpoints

GET http://localhost:8080/
Accept: application/json

###

GET http://localhost:8080/health
Accept: application/json

###

GET http://localhost:8080/health/db
Accept: application/json

###

POST http://localhost:8080/health/echo
Content-Type: application/json

{
  "key": "value",
  "list": [
    1,
    2,
    3
  ]
}

###

GET http://localhost:8080/v1/analysis?q=ПЦР&city=Москва
Content-Type: application/json

###

GET http://localhost:8080/v1/analysis/d13b509a-9d02-49a3-be71-96fcb80c4c37
Content-Type: application/json

###

GET http://localhost:8080/v1/city
Content-Type: application/json

###

POST http://localhost:8080/v1/user/register
Content-Type: application/json

{
  "email": "king.arthur@camelot.bt",
  "name": "Artur",
  "password": "guinevere"
}

###

POST http://localhost:8080/v1/user/jwt/login
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="username"

king.arthur@camelot.bt

--boundary
Content-Disposition: form-data; name="password"

guinevere
--boundary--

###

GET http://localhost:8080/v1/user/jwt/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

###

GET http://localhost:8080/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

###

GET http://localhost:8080/v1/personal/sugar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

###

POST http://localhost:8080/v1/personal/sugar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

{
  "value": 5.9
}

###

DELETE http://localhost:8080/v1/personal/sugar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

{
  "id": "451ea894-1593-42c6-a674-4ea0b54e13d5"
}

###

GET http://localhost:8080/v1/personal/custom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

###

GET http://localhost:8080/v1/personal/custom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

{
  "name": "Сахар в крови"
}

###

GET http://localhost:8080/v1/personal/custom?name=Сахар%20в%20крови
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

###

POST http://localhost:8080/v1/personal/custom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

{
  "name": "Белки в крови",
  "unit": "г/л",
  "value": 8
}

###

DELETE http://localhost:8080/v1/personal/custom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQyMjEwfQ.FiKyXesMzOlbu3eTu5_ixPZXI1xwTOBue5QEBnEFkx8
Content-Type: application/json

{
  "id": "3f160ec9-acde-4e50-9e52-bae3bf2fcbb7"
}

###

GET http://localhost:8080/v1/personal/follow-history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQ3MjExfQ.2nDClkdaw7i-d561zUkQvOweA_a25YqtnzCkldOhmHQ
Content-Type: application/json

###

POST http://localhost:8080/v1/personal/follow-history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImF1ZCI6WyJmYXN0YXBpLXVzZXJzOmF1dGgiXSwiZXhwIjoxNjc0NzQ3MjExfQ.2nDClkdaw7i-d561zUkQvOweA_a25YqtnzCkldOhmHQ
Content-Type: application/json

{
  "link": "https://www.youtube.com/watch?v=QH2-TGUlwu4"
}

###
